### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by scannopolis**

### CODE REVIEW

**Comment by anarchivist** [comment]
Hello @scannopolis - thanks for the contribution. I have let my colleagues know about your contribution. It may take some time for us to review it.

**Comment by aisaac** [comment]
@paul2keller @juliafallon Would you like to chime in?

**Comment by scannopolis** [comment]
I think that the latest translation though is available here and not in this repo: https://docs.google.com/document/d/1wzPVyHAFO4Uke_fVSlQfZtG-mQAHQFcE2PaM86TRweU/edit#

**Comment by paul2keller** [comment]
yes the google doc that @scannopolis is referencing above is the current version of the translation (almost ready for public consultation)

**Pull request closed without merging**
