### PR TITLE
Transifex

### PR DESCRIPTION
**Pull request by literarymachine**
Move descriptive text to language specific JSON-LD files and add configuration for [`tx`](https://docs.transifex.com/client/introduction).

### CODE REVIEW

**Review by anarchivist — CHANGES_REQUESTED** [review]
As discussed on the call on 4 June, we should split the JSON files into one per language per statement. 

We also may want to look into determining if Transifex will allow us to reuse translations across files. For example, all but two of the statements (InC-OW-EU and InC-RUU) use the same set of "notices" (`skos:note`). The two exceptions just add an additional `skos:note` to the other three.

**Comment by aisaac** [comment]
I've done a very partial review this morning and two questions come to mind for the moment:
- the translations could be grouped in folders (language-specific): is it s good or bad idea? I fear I don't know all the implications of changing the folder structure.
- in the documentation, what does "An example file, which contains rights statements with a different version and containing sample, unofficial translations, can be found in example-versions.ttl." mean? And do we want to still refer to Turtle files?

I've got another point which is probably better fit for live discussion, but as I don't know whether I can attend this afternoon's call I'm going to note it here now. It's about the ordering of the statements in each of the file. As discussed in our last call this would be desirable for translators. I guess it should be done manually. I don't mind trying it myself, but is it doable on the files at this stage?

**Comment by literarymachine** [comment]
> the translations could be grouped in folders (language-specific): is it s good or bad idea? I fear I don't know all the implications of changing the folder structure.

Grouping them in language-specific folders in the data-model repository would not be a big deal.

> in the documentation, what does "An example file, which contains rights statements with a different version and containing sample, unofficial translations, can be found in example-versions.ttl." mean? And do we want to still refer to Turtle files

I was also wondering if it would not be a good moment to remove `example-versions.ttl`. It was introduced before I entered the project, but the way I understood it is that it was supposed to guide translations. These will now be carried out in transifex.

As for turtle files in general, we currently still take them into account. I have only moved data that is relevant for translation to JSON-LD, the main structure is still encoded in [rights-statements.ttl ](https://github.com/literarymachine/data-model/blob/transifex/rights-statements.ttl). We could of course change that.

**Comment by aisaac** [comment]
+1 for removing example-versions.ttl
And indeed we keep rights-statements.ttl for the time being.

**Comment by anarchivist** [comment]
I believe `example-versions.ttl` was intended to demonstrate that two features were working (versions and translations) before we had any official examples of either.

**Comment by literarymachine** [comment]
> It's about the ordering of the statements in each of the file.

@aisaac: I believe it was about ordering the properties of the statements in each file, right?

> As discussed in our last call this would be desirable for translators. I guess it should be done manually. I don't mind trying it myself, but is it doable on the files at this stage?

Yes, this would probably be a good moment to do this. If you specify the desired order, I could rearrange them programmatically. The keys for the individual statements are `description`, `definition`, `note`, `prefLabel` and `scopeNote`. For the collections there is only `prefLabel`. In both cases, there are also `@context.@vocab`, `@context.@language`, `@context.description` and `@id`, which are necessary JSON-LD metadata. We should probably move these to the end?

**Comment by aisaac** [comment]
@literarymachine re the order, in general it should be the one reflected on the pages and translation documents like https://docs.google.com/document/d/1t5Pe5Kz8jAKsTeveFpihD4zvR5p7Z9aNWf60tZyhwfg/

So for regular statements the order is
- prefLabel
- description
- definition
- note
- scopeNote
(and then there should be the labels for the notes on extra metadata or deprecation dates, but as they are stored somewhere else in our code I guess we have no choice but to have them separately)

Regarding the context, it seems fine to keep it at the top. I guess this is the convention, no? At least this is what I've seen most often. But I guess it doesn't matter from a JSON-LD perspective so I'm fine either way.

**Comment by literarymachine** [comment]
@anarchivist This one is also ready to merge.

**Review by anarchivist — APPROVED** [review]

**Pull request merged**
