### PR TITLE
Add Estonian translation and reorganize assertions (for easier translation)

### PR DESCRIPTION
**Pull request by anarchivist**
Ref rightsstatements/rightsstatements.github.io#141

### CODE REVIEW

**Review by aisaac — APPROVED** [review]
I've not had the time to compare with the PDF document for the translation. But I've checked the new organization and the consistency of the new statements.

In general it is good, and I like the new organization!

The one potential issue I saw is about encoding of Estonian diacritics, which not consistently displayed by github on Firefox: for example autorio˜igusliku at the beginning (l35) became autoriõigusliku  (l191 and after). Which one should be the correct way? The confusing thing is that in the raw file, the difference does not seem to be visible anymore, in Firefox, Textedit or Aquamacs or more command line. So I'm going to merge, assuming that if there's a difference it won't be seen for most cases, and we can fix it later.

There are two other minor issues/comments, which could also be fixed afterwards: 
- InC-EDU/1.0/ statements miss their "descriptive text" structuring comment
- I would have grouped the skos:inScheme statement with the other "term-level metadata" statements.
-

**Comment by aisaac** [comment]
@anarchivist I'm just keeping the branch because I don't know what's going to happen with my review after it's deleted in github. Sorry for the github ignorance...

**Comment by puik** [comment]
@anarchivist, @aisaac please tag me when something about Estonian translation needs to checked or tested.

**autorio˜igusliku** – wrong
**autoriõigusliku** – correct

The [**final pdf**](https://github.com/rightsstatements/rightsstatements.github.io/files/2076101/180606RS_1.0_translation_EE_approved.pdf) is the reference.

**Comment by aisaac** [comment]
@puik thanks, I had no doubt that autorio˜igusliku would be wrong. The thing is that I see it in only one of the 5 displays I've seen. So I'm not even sure what kind of problem it could be - in some case we had to 'escape' characters to meet encoding requirements, maybe this is what happened here. In anycase it's a problem of encoding not of not knowing what is the correct word.

**Comment by anarchivist** [comment]
this seems to be an issue regarding a difference between the use of a combining vs. noncombining tilde.

@puik I will be submitting a revision shortly; please check based on the email i copy you on.

**Pull request merged**
