### PR TITLE
Update to published text of Rights Statements

### PR DESCRIPTION
**Pull request by musebrarian**
Update SKOS definitions and notes to conform to the published Rights
Statements document.
http://rightsstatements.org/files/151002recommendations_for_standardized
_international_rights_statements.pdf

### CODE REVIEW

**Comment by anarchivist** [comment]
Hi @musebrarian - it looks like there's a typo on line 95. Can you fix this up and we can take another look for the review?

**Comment by musebrarian** [comment]
Fixed typo on line 95.

**Comment by anarchivist** [comment]
Unless I'm missing something, the change didn't show up...

**Comment by musebrarian** [comment]
@anarchivist  Hmm, can you see this commit?  https://github.com/rightsstatements/data-model/commit/f28756d7ee70d17940b7a5ebf6db9d63b7cc4620 
It seems to be part of this same pull request and I can't make a new one for this last fix (maybe because this branch was never merged?)

**Comment by anarchivist** [comment]
I can see it now - thanks!

**Pull request merged**
