### PR TITLE
Add UND statement

### PR DESCRIPTION
**Pull request by anarchivist**
Based on confirmed text [on Google Drive](https://docs.google.com/document/d/1EQng3F8bRW6BAy9uWjgdSXjs3WZQ2Lv8eJvfvwDRVbk/edit)

### CODE REVIEW

**Comment by escowles** [comment]
I have a question about capitalization: should it be "Und" instead of "UND"? Almost all of the other names are all-caps only when they are acronyms, and otherwise mixed case, e.g., "InC" for "In Copyright".  I say almost all because there is one exception: "EDU" for "Educational".

**Comment by no-reply** [comment]
:+1: Looks good to me. (Pending @escowles's question).

We agreed in the previous WG meeting that this wouldn't require a version bump for the statements. I've since done a bit of reading on the subject and think I have confirmed that this is a good strategy. 

I want to advance the general principle that the simple addition of statements never requires a version change. The reasoning is that these additions support _prospective use_ as discussed in [**Ontology Versioning on the Semantic Web**](https://files.ifi.uzh.ch/ddis/iswc_archive/iswc/ih/SWWS-2001/program/full/paper56a.pdf). Specifically, additions won't ever change interpretations for existing users; bumping the version creates more work for those users.

**Comment by anarchivist** [comment]
@escowles My argument for `UND` would be that it follows the pattern of the rest of the "other" statements (i.e. `NKC` and `CNE`), even though though it is not an acronym.

+1 to @no-reply's change, although that should be probably opened as a new issue and discussed on a call.

**Comment by anarchivist** [comment]
I forced push a change (the statement URI was missing its trailing slash).

**Comment by escowles** [comment]
👍  — I'm fine with all-caps "UND"

I also agree with @no-reply's point about additions not requiring a new version, and that it should be a separate issue.

**Comment by no-reply** [comment]
> I also agree with @no-reply's point about additions not requiring a new version, and that it should be a separate issue.

I'll raise it. I wanted to make sure it got mentioned here to give everyone the opportunity to disagree w.r.t. this PR.

**Comment by paul2keller** [comment]
with regards to Capitalization i am also in support of Capitalizing UND. NoC and InC are written that way because that makes them more readable (writing out the first word and then having a capital C for copyright)

I also think that additions not requiring a new version is the correct approach, but i want to caution here that this is not only a data modeling / technical issue and needs broader discussion. We are currently working on a editorial/procedural guidlines for changes/additions to the statements and the question of versioning will need to be adressed in that context. (but we have agreed that for now the addition of UND should not result in a new version)

**Comment by mzeinstra** [comment]
👍 I have no additional comments. I agree with the outcome of the discussion above.

**Comment by aisaac** [comment]
Sorry for the late reaction. I think the suggested addition is very fine.

I am a bit worried about saying that any simple addition doesn't need a version change. After many simple additions a vocabulary could have dozens of new resources. Or new resources could influence the use (in 'instance' data) of existing ones, even without changing their definitions. (This is the case when introducing narrower concepts to a leaf concept, for instance.)
But anyway this is not our case here of course.

**Comment by paul2keller** [comment]
that raises an interesting question: what exactely are we versionining when we talk about versioning here. To me @aisaac's comment sounds like he is talking about versioning the vocabulary, while i (and probably many others) think about versioning individual statements (which would most likely happen to all of them at the same time, but stil te version would be a property of the statement as it is practiced by Creative Commons)

**Comment by aisaac** [comment]
Even at individual level, depending on the severity of the change, changing only one statement could affect the way others are used, even though the definition of these ones wouldn't be explicitly changed.
I'm probably talking about corner cases, but there's a chance. At least it happens often in thesauri and other vocabularies, when adding new concepts as specializations of existing ones.

**Comment by escowles** [comment]
I think Antoine makes a good point here — so maybe the rule should be that additions don't require a new version of the vocabulary, unless the additions are significant enough to change the nature of the vocabulary as a whole.

## -Esmé

escowles@ticklefish.org

**Comment by kestlund** [comment]
I'd like to move forward on this pull request, but I'm also want to make sure we don't lose these important discussion points.  (BTW: I do like UND all caps.)

I would like to propose the following:
1. Merge this pull request
2. Create a new Github issue on "versioning" (citing this thread) and link to a Google Doc that has many of these points, as well as the outline from our original tech document and highlights from our last call. It can then be commented on by the tech group and governance groups to further progress.

**Comment by musebrarian** [comment]
@no-reply  thanks for the reference.  

I'm +1 for all CAPS "UND"

I feel like we discussed vocabulary vs. statement versioning before and decided to version the vocabulary until we had further examples of why we'd version statements.  I have some other questions about versioning that I'll save for the separate thread.

**Comment by escowles** [comment]
👍  to @kestlund's suggestion — I've created issue #52 for discussing the versioning policy, and it includes a link to an open Google Doc that contains the current versioning policy.

**Pull request merged**
